name: scrape

on:
  schedule:
    - cron: '*/15 * * * *'          # every 15 min
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}

      - name: Install deps
        run: pip install -r scrapers/requirements.txt

      - name: Scrape & ingest
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          APIFY_TOKEN:  ${{ secrets.APIFY_TOKEN }}
        run: python scrapers/main.py
